### Create pet
POST http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTczODU4MDA2NSwiZXhwIjoxNzM4NTgzNjY1fQ._hkRtquBy8nZMjGKGRIdEpiSsz1DRWqSxgEmT2aba8Y
Content-Type: application/json

{
  "name": "Floffy"
}

### Get pet
GET http://localhost:8080/users/pet
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTczODU3ODkwMCwiZXhwIjoxNzM4NTgyNTAwfQ.2ijuAuYHA6_laDQFx8wHi5SzDla-IaoCfKW3RhMx8is

